### ISSUE TITLE
Lost in Linux

### ISSUE THREAD

**Issue by keithterrill** [wejgaard/TclForth#5]
I am totally lost in how to get this going in my Linux (mint). The directions are a little scant for me. I downloaded the Tclforth.zip and Source code (zip) for Tclforth v0.7.0.

I open a terminal and changed director to the source directory. But, the Linux directions "source tfmain.tcl" has me stymied.

Can someone please hold my hand in getting something up and running? I have been using tkinter in python and want to try it in forth.

Once upon a time, back in the 1980's I created a forth compiler for a DataGeneral s/200 and also for a z80 computer. I just installed swiftforth and have been re-learning forth.

Any help to just get this up and running would be appreciated. thank you.

**Comment by wejgaard** [comment]
Run tclforthx in a terminal. It opens the Tcl console, IOW it is Tcl.
You could also open the Tcl system in the Linux distribution, if present.
In Tcl "cd " to the source directory in the Tclforth release. 
Then "source tfmain.tcl" loads Tclforth. 
("source" is a Tcl command.)
Hope it works now.

**Comment by keithterrill** [comment]
So, I open a terminal. I changed mode for tclforthx to executable. Then I did:

`$ ./tclforthx

couldn't change working directory to "../../../../source": no such file or directory while executing
"cd ../../../../source"
    (file "/home/share/program/forth/TclForth/source/tclforthx/main.tcl" line 4)

$
`

**Comment by keithterrill** [comment]
In a terminal I was able to run tclsh. 
`% info patchlevel
8.6.1
`
source tfmain.tcl launched the TclForth Version 0.7.0
