### ISSUE TITLE
Forth tag

### ISSUE THREAD

**Issue by FForth** [wejgaard/TclForth#6]
Please create a "Forth" tag and ... for this project.

**Comment by wejgaard** [comment]
Please tell me how to do it.

**Comment by FForth** [comment]
Please have a look at the https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics — the topics describe a repository in GitHub.

**Comment by FForth** [comment]
Label "Manage topic" in open project

**Comment by wejgaard** [comment]
Thank you. Done.
